#!/usr/bin/env python3

from books import Books

# Set PAPERS_DIR
if Books.on_wsl():
    # work
    PAPERS_DIR = '/home/nvasilas/docs/papers'
else:
    # home
    PAPERS_DIR = '/home/nikos/docs/papers'


Books(PAPERS_DIR).run()
